import '../../domain/entities/budget_entity.dart';
import '../../domain/entities/transaction_entity.dart';

/// Insight types generated by the engine.
enum InsightType {
  categoryOverspend,
  budgetForecast,
  topSpendingDay,
  savingsUp,
  savingsDown,
  topCategory, // WS-11
  transactionStreak, // WS-11
  noIncomeRecorded, // WS-11
}

/// A single insight produced by [InsightEngine].
class Insight {
  const Insight({
    required this.type,
    required this.params,
  });

  final InsightType type;

  /// Key-value parameters for l10n interpolation.
  /// e.g. {'category': 'Food', 'percent': 35}
  final Map<String, dynamic> params;
}

/// Pure Dart insight computation — no Flutter, no internet.
/// Takes raw data and produces a list of [Insight]s.
class InsightEngine {
  const InsightEngine._();

  /// Generate all applicable insights from the given data.
  ///
  /// [allRecentTxns] should include at least 2 months of transactions
  /// (used for week-based calculations that may cross month boundaries).
  static List<Insight> generate({
    required List<TransactionEntity> thisMonthTxns,
    required List<TransactionEntity> lastMonthTxns,
    required List<BudgetEntity> budgets,
    required Map<int, String> categoryNames,
    List<TransactionEntity>? allRecentTxns,
  }) {
    final insights = <Insight>[];

    // 1. Category overspend (spending > 120% of last month average)
    insights.addAll(
      _categoryOverspend(thisMonthTxns, lastMonthTxns, categoryNames),
    );

    // 2. Budget forecast (projected to exceed by month end)
    insights.addAll(_budgetForecast(budgets, categoryNames));

    // 3. Top spending day of the week
    final topDay = _topSpendingDay(thisMonthTxns);
    if (topDay != null) {
      insights.add(topDay);
    }

    // 4. Monthly savings comparison
    final savings = _savingsComparison(thisMonthTxns, lastMonthTxns);
    if (savings != null) {
      insights.add(savings);
    }

    // 5. WS-11: Top spending category this month
    final topCat = _topCategory(thisMonthTxns, categoryNames);
    if (topCat != null) {
      insights.add(topCat);
    }

    // 6. WS-11: Transaction streak this week
    // Use allRecentTxns (both months) so week boundary crossing works correctly.
    final streak = _transactionStreak(allRecentTxns ?? thisMonthTxns);
    if (streak != null) {
      insights.add(streak);
    }

    // 7. WS-11: No income recorded after day 10
    final noIncome = _noIncomeRecorded(thisMonthTxns);
    if (noIncome != null) {
      insights.add(noIncome);
    }

    return insights;
  }

  /// Categories where this month's spending is > 120% of last month.
  static List<Insight> _categoryOverspend(
    List<TransactionEntity> thisMonth,
    List<TransactionEntity> lastMonth,
    Map<int, String> categoryNames,
  ) {
    final thisExpenses = _expenseByCat(thisMonth);
    final lastExpenses = _expenseByCat(lastMonth);

    final results = <Insight>[];
    for (final entry in thisExpenses.entries) {
      final lastAmount = lastExpenses[entry.key] ?? 0;
      if (lastAmount == 0) continue;

      final ratio = entry.value / lastAmount;
      if (ratio > 1.2) {
        final percent = ((ratio - 1) * 100).round();
        final name = categoryNames[entry.key] ?? '?';
        results.add(
          Insight(
            type: InsightType.categoryOverspend,
            params: {'category': name, 'percent': percent},
          ),
        );
      }
    }
    return results;
  }

  /// Budgets projected to exceed by month end based on current pace.
  static List<Insight> _budgetForecast(
    List<BudgetEntity> budgets,
    Map<int, String> categoryNames,
  ) {
    final now = DateTime.now();
    final dayOfMonth = now.day;
    final daysInMonth = DateTime(now.year, now.month + 1, 0).day;
    if (dayOfMonth < 5) return []; // too early to forecast

    final results = <Insight>[];
    for (final budget in budgets) {
      if (budget.effectiveLimit <= 0) continue;

      final dailyRate = budget.spentAmount / dayOfMonth;
      final projected = (dailyRate * daysInMonth).round();

      if (projected > budget.effectiveLimit && !budget.isOverBudget) {
        final name = categoryNames[budget.categoryId] ?? '?';
        results.add(
          Insight(
            type: InsightType.budgetForecast,
            params: {'category': name},
          ),
        );
      }
    }
    return results;
  }

  /// The weekday with highest total spending this month.
  static Insight? _topSpendingDay(List<TransactionEntity> txns) {
    final expenses = txns.where((tx) => tx.type == 'expense');
    if (expenses.length < 3) return null; // WS-11: lowered from 7 to 3

    // dayOfWeek: 1=Mon, 7=Sun
    final byDay = <int, int>{};
    for (final tx in expenses) {
      final dow = tx.transactionDate.weekday;
      byDay[dow] = (byDay[dow] ?? 0) + tx.amount;
    }

    if (byDay.isEmpty) return null;

    final topEntry = byDay.entries.reduce(
      (a, b) => a.value >= b.value ? a : b,
    );

    return Insight(
      type: InsightType.topSpendingDay,
      params: {'dayIndex': topEntry.key},
    );
  }

  /// Compare net savings (income - expense) this month vs last.
  static Insight? _savingsComparison(
    List<TransactionEntity> thisMonth,
    List<TransactionEntity> lastMonth,
  ) {
    final thisNet = _netSavings(thisMonth);
    final lastNet = _netSavings(lastMonth);

    // I11 fix: guard against division by near-zero (< 1 EGP = 100 piastres)
    if (lastNet.abs() < 100) return null;

    final diff = thisNet - lastNet;
    final rawPct = ((diff / lastNet.abs()) * 100).round().abs();
    // I11 fix: cap percentage at 1000% to avoid misleading outliers
    final pct = rawPct > 1000 ? 1000 : rawPct;
    if (pct < 5) return null; // ignore tiny changes

    if (diff > 0) {
      return Insight(
        type: InsightType.savingsUp,
        params: {'percent': pct},
      );
    } else {
      return Insight(
        type: InsightType.savingsDown,
        params: {'percent': pct},
      );
    }
  }

  /// WS-11: Top spending category this month (needs >= 2 expenses).
  static Insight? _topCategory(
    List<TransactionEntity> txns,
    Map<int, String> categoryNames,
  ) {
    final expensesByCat = _expenseByCat(txns);
    if (expensesByCat.length < 2) return null;

    final top = expensesByCat.entries.reduce(
      (a, b) => a.value >= b.value ? a : b,
    );
    final name = categoryNames[top.key] ?? '?';
    final total = expensesByCat.values.fold<int>(0, (s, e) => s + e);
    final percent = total > 0 ? ((top.value / total) * 100).round() : 0;

    return Insight(
      type: InsightType.topCategory,
      params: {'category': name, 'percent': percent},
    );
  }

  /// WS-11: Transaction streak — logged >= 3 transactions this week.
  static Insight? _transactionStreak(List<TransactionEntity> txns) {
    final now = DateTime.now();
    final weekStart = now.subtract(Duration(days: now.weekday - 1));
    final startOfWeek = DateTime(weekStart.year, weekStart.month, weekStart.day);

    final thisWeek = txns.where(
      (tx) => tx.transactionDate.isAfter(startOfWeek) ||
          tx.transactionDate.isAtSameMomentAs(startOfWeek),
    );
    final count = thisWeek.length;
    if (count < 3) return null;

    return Insight(
      type: InsightType.transactionStreak,
      params: {'count': count},
    );
  }

  /// WS-11: No income recorded after day 10 of the month.
  static Insight? _noIncomeRecorded(List<TransactionEntity> txns) {
    final now = DateTime.now();
    if (now.day <= 10) return null;

    final hasIncome = txns.any((tx) => tx.type == 'income');
    if (hasIncome) return null;

    return const Insight(
      type: InsightType.noIncomeRecorded,
      params: {},
    );
  }

  // ── Helpers ──────────────────────────────────────────────────────────────

  static Map<int, int> _expenseByCat(List<TransactionEntity> txns) {
    final map = <int, int>{};
    for (final tx in txns) {
      if (tx.type == 'expense') {
        map[tx.categoryId] = (map[tx.categoryId] ?? 0) + tx.amount;
      }
    }
    return map;
  }

  static int _netSavings(List<TransactionEntity> txns) {
    var income = 0;
    var expense = 0;
    for (final tx in txns) {
      if (tx.type == 'income') {
        income += tx.amount;
      } else {
        expense += tx.amount;
      }
    }
    return income - expense;
  }
}
